services:
  inventario_api:
    container_name: inventario_api
    build: 
      context: .
      dockerfile: Dockerfile
    image: inventario_api:latest
    ports:
      - "8080:8080"
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - ASPNETCORE_ENVIRONMENT=Development